// Client-safe i18n dictionary (no server-only imports — usable in client components).
export type Locale = "en" | "vi";
export const LOCALES: Locale[] = ["en", "vi"];
export const LOCALE_COOKIE = "locale";

export const dict = {
  en: {
    // nav
    navHome: "Home",
    navPeople: "Members",
    navPublications: "Publications",
    navConferences: "Conferences",
    navAwards: "Awards",
    navDatasets: "Datasets",
    navContact: "Contact",

    // common
    featured: "Featured",
    viewAll: "View all",
    allMembers: "All members →",
    visit: "Visit ↗",
    tba: "TBA",
    getInTouch: "Get in touch",

    // home
    heroCtaResearch: "Read our research",
    heroCtaTeam: "Meet the team",
    nextUp: "Next up",
    badgeDeadline: "Deadline",
    badgeConference: "Conference",
    submissionCloses: "Submission closes",
    starts: "Starts",
    allConfDeadlines: "All conferences & deadlines →",
    noUpcoming: "No upcoming deadlines",
    manageConferences: "Manage conferences →",
    sFocus: "Focus",
    sAffiliation: "Affiliation",
    sActiveSince: "Active since",
    aboutEyebrow: "About the lab",
    aboutHeading: "Models that see, read, and retrieve.",
    featuredWork: "Featured work",
    areasEyebrow: "What we work on",
    areasHeading: "Research areas",
    deadlinesEyebrow: "Deadlines",
    upcomingConferences: "Upcoming conferences",
    teamEyebrow: "The team",
    peopleHeading: "Members",
    newsEyebrow: "News",
    latest: "Latest",
    ctaHeading: "Interested in working with us?",
    ctaBody: "We welcome students and collaborators in computer vision and retrieval. Reach out to the team.",
    noPubs: "No publications yet.",
    noNews: "No news yet.",

    // people
    peopleSubtitle: "Faculty, researchers and students behind CORE Lab.",
    grpFaculty: "Faculty & Advisors",
    grpCollaborator: "Collaborating Professors",
    grpMember: "Research Members",
    grpStudent: "Students",
    grpAlumni: "Alumni",
    peopleEmpty: "No members yet.",
    linkScholar: "Scholar",
    linkHomepage: "Homepage",
    linkGithub: "GitHub",
    linkLinkedin: "LinkedIn",

    // publications
    pubsEyebrow: "Research",
    pubsSubtitle: "Peer-reviewed work from CORE Lab in computer vision and retrieval.",
    viewHighlights: "View highlights",
    pdf: "PDF",
    code: "Code",
    projectPage: "Project page",
    pubsEmpty: "No publications yet.",
    pubSearch: "Search title or author…",
    pubAllAuthors: "All authors",
    pubAllVenues: "All venues",
    pubClear: "Clear filters",
    pubNoMatch: "No publications match your filters.",
    pubCount: "publications",
    pubPrev: "Prev",
    pubNext: "Next",

    // publication detail
    allPublications: "← All publications",
    abstract: "Abstract",
    overview: "Overview",
    figures: "Figures",
    results: "Results",
    highlights: "Highlights",
    fullPaper: "Full paper",
    fullPaperBodyPre: "The full manuscript is kept private. For the PDF or collaboration, please ",
    contactTheTeam: "contact the team",
    fig: "Fig.",

    // conferences
    confEyebrow: "Deadlines & dates",
    confHeading: "Upcoming conferences",
    confSubtitle: "Live countdowns to the deadlines and dates CORE Lab is targeting.",
    nextDeadline: "Next deadline",
    nextConference: "Next conference",
    upcoming: "Upcoming",
    untilDeadline: "Until deadline",
    untilStart: "Until start",
    paperDeadline: "Paper deadline",
    conference: "Conference",
    confEmpty: "No conferences yet.",

    // awards
    awardsEyebrow: "Honors & recognition",
    awardsHeading: "Awards",
    awardsSubtitle:
      "Recognized at international and national competitions in AI, computer vision and video retrieval.",
    awTotal: "Awards won",
    awFirstPrizes: "First prizes",
    awYears: "Years active",
    awEmpty: "No awards yet.",
    datasetsEyebrow: "Open data",
    datasetsTitle: "Datasets",
    datasetsSubtitle:
      "Datasets we have published — explore a few samples, then request the full release.",
    dsAbout: "About",
    dsSamples: "Samples",
    dsExplore: "Explore full dataset ↗",
    dsPaper: "Paper ↗",
    dsCode: "Code ↗",
    dsLicense: "License & access",
    dsDetected: "Recognized text",
    dsShow: "Show text",
    dsHide: "Hide text",
    dsRegion: "regions",
    dsView: "View dataset",
    dsEmpty: "No datasets yet.",

    // countdown
    cdDays: "Days",
    cdHrs: "Hrs",
    cdMin: "Min",
    cdSec: "Sec",
    cdDeadlinePassed: "Deadline passed",
    cdHappening: "Happening now / passed",
    cdClosed: "Closed / past",

    // contact
    contactEyebrow: "Contact",
    contactHeading: "Get in touch with the team.",
    contactSubtitle: "Questions, collaborations, or interested in joining CORE Lab? Send us a note.",
    cPI: "Principal Investigator",
    cPINote:
      "For collaborations, student supervision, or dataset requests, reach out to the PI directly.",
    cEmail: "Email",
    cAffiliation: "Affiliation",
    cAddress: "Address",
    cLocation: "Location",
    fName: "Name",
    fYourEmail: "Your email",
    fSubject: "Subject",
    fMessage: "Message",
    fSend: "Send message",
    fNotePre: "This opens your email client addressed to ",

    // footer
    footerLab: "Lab",
    footerConnect: "Connect",
  },

  vi: {
    navHome: "Trang chủ",
    navPeople: "Thành viên",
    navPublications: "Công bố",
    navConferences: "Hội nghị",
    navAwards: "Giải thưởng",
    navDatasets: "Bộ dữ liệu",
    navContact: "Liên hệ",

    featured: "Nổi bật",
    viewAll: "Xem tất cả",
    allMembers: "Tất cả thành viên →",
    visit: "Truy cập ↗",
    tba: "Chưa có",
    getInTouch: "Liên hệ",

    heroCtaResearch: "Xem nghiên cứu",
    heroCtaTeam: "Gặp đội ngũ",
    nextUp: "Sắp tới",
    badgeDeadline: "Hạn nộp",
    badgeConference: "Hội nghị",
    submissionCloses: "Đóng nộp bài",
    starts: "Bắt đầu",
    allConfDeadlines: "Tất cả hội nghị & hạn nộp →",
    noUpcoming: "Chưa có hạn nộp sắp tới",
    manageConferences: "Quản lý hội nghị →",
    sFocus: "Lĩnh vực",
    sAffiliation: "Đơn vị",
    sActiveSince: "Hoạt động từ",
    aboutEyebrow: "Về phòng lab",
    aboutHeading: "Mô hình biết nhìn, đọc và truy xuất.",
    featuredWork: "Công trình nổi bật",
    areasEyebrow: "Chúng tôi nghiên cứu",
    areasHeading: "Hướng nghiên cứu",
    deadlinesEyebrow: "Hạn nộp",
    upcomingConferences: "Hội nghị sắp tới",
    teamEyebrow: "Đội ngũ",
    peopleHeading: "Thành viên",
    newsEyebrow: "Tin tức",
    latest: "Mới nhất",
    ctaHeading: "Muốn hợp tác cùng chúng tôi?",
    ctaBody: "Chúng tôi chào đón sinh viên và cộng tác viên trong lĩnh vực thị giác máy tính và truy xuất. Hãy liên hệ với đội ngũ.",
    noPubs: "Chưa có công bố.",
    noNews: "Chưa có tin tức.",

    peopleSubtitle: "Giảng viên, nghiên cứu viên và sinh viên của CORE Lab.",
    grpFaculty: "Giảng viên & Cố vấn",
    grpCollaborator: "Giáo sư cộng tác",
    grpMember: "Nghiên cứu viên",
    grpStudent: "Sinh viên",
    grpAlumni: "Cựu thành viên",
    peopleEmpty: "Chưa có thành viên.",
    linkScholar: "Scholar",
    linkHomepage: "Trang cá nhân",
    linkGithub: "GitHub",
    linkLinkedin: "LinkedIn",

    pubsEyebrow: "Nghiên cứu",
    pubsSubtitle: "Các công bố của CORE Lab về thị giác máy tính và truy xuất.",
    viewHighlights: "Xem chi tiết",
    pdf: "PDF",
    code: "Mã nguồn",
    projectPage: "Trang dự án",
    pubsEmpty: "Chưa có công bố.",
    pubSearch: "Tìm theo tiêu đề hoặc tác giả…",
    pubAllAuthors: "Tất cả tác giả",
    pubAllVenues: "Tất cả hội nghị",
    pubClear: "Xoá bộ lọc",
    pubNoMatch: "Không có công bố nào khớp bộ lọc.",
    pubCount: "công bố",
    pubPrev: "Trước",
    pubNext: "Sau",

    allPublications: "← Tất cả công bố",
    abstract: "Tóm tắt",
    overview: "Tổng quan",
    figures: "Hình ảnh",
    results: "Kết quả",
    highlights: "Điểm nổi bật",
    fullPaper: "Toàn văn",
    fullPaperBodyPre: "Bản thảo đầy đủ được giữ riêng tư. Để nhận PDF hoặc hợp tác, vui lòng ",
    contactTheTeam: "liên hệ với đội ngũ",
    fig: "Hình",

    confEyebrow: "Hạn nộp & ngày tổ chức",
    confHeading: "Hội nghị sắp tới",
    confSubtitle: "Đếm ngược trực tiếp đến các hạn nộp và ngày mà CORE Lab hướng tới.",
    nextDeadline: "Hạn nộp kế tiếp",
    nextConference: "Hội nghị kế tiếp",
    upcoming: "Sắp tới",
    untilDeadline: "Đến hạn nộp",
    untilStart: "Đến ngày bắt đầu",
    paperDeadline: "Hạn nộp bài",
    conference: "Hội nghị",
    confEmpty: "Chưa có hội nghị.",

    awardsEyebrow: "Vinh danh & thành tích",
    awardsHeading: "Giải thưởng",
    awardsSubtitle:
      "Được vinh danh tại các cuộc thi quốc tế và trong nước về AI, thị giác máy tính và truy hồi video.",
    awTotal: "Giải thưởng",
    awFirstPrizes: "Giải Nhất",
    awYears: "Năm hoạt động",
    awEmpty: "Chưa có giải thưởng.",
    datasetsEyebrow: "Dữ liệu mở",
    datasetsTitle: "Bộ dữ liệu",
    datasetsSubtitle:
      "Các bộ dữ liệu chúng tôi đã công bố — xem một vài mẫu, sau đó yêu cầu bản đầy đủ.",
    dsAbout: "Giới thiệu",
    dsSamples: "Mẫu dữ liệu",
    dsExplore: "Khám phá toàn bộ dữ liệu ↗",
    dsPaper: "Bài báo ↗",
    dsCode: "Mã nguồn ↗",
    dsLicense: "Giấy phép & truy cập",
    dsDetected: "Văn bản nhận dạng",
    dsShow: "Hiện văn bản",
    dsHide: "Ẩn văn bản",
    dsRegion: "vùng",
    dsView: "Xem bộ dữ liệu",
    dsEmpty: "Chưa có bộ dữ liệu.",

    cdDays: "Ngày",
    cdHrs: "Giờ",
    cdMin: "Phút",
    cdSec: "Giây",
    cdDeadlinePassed: "Đã hết hạn",
    cdHappening: "Đang diễn ra / đã qua",
    cdClosed: "Đã đóng / đã qua",

    contactEyebrow: "Liên hệ",
    contactHeading: "Liên hệ với đội ngũ.",
    contactSubtitle: "Có câu hỏi, muốn hợp tác, hay quan tâm gia nhập CORE Lab? Hãy gửi lời nhắn.",
    cPI: "Chủ nhiệm nhóm nghiên cứu",
    cPINote:
      "Để hợp tác, hướng dẫn sinh viên hoặc yêu cầu bộ dữ liệu, hãy liên hệ trực tiếp với người phụ trách.",
    cEmail: "Email",
    cAffiliation: "Đơn vị",
    cAddress: "Địa chỉ",
    cLocation: "Địa điểm",
    fName: "Họ tên",
    fYourEmail: "Email của bạn",
    fSubject: "Tiêu đề",
    fMessage: "Nội dung",
    fSend: "Gửi lời nhắn",
    fNotePre: "Thao tác này mở ứng dụng email tới ",

    footerLab: "Phòng lab",
    footerConnect: "Kết nối",
  },
};

export type Dict = (typeof dict)["en"];

export function getDict(locale: Locale): Dict {
  return dict[locale] ?? dict.en;
}
